#!/bin/bash

# Define the SSH connection parameters
SSH_USER="devops"
SSH_HOST="172.16.174.108"

# Define the remote script to execute
REMOTE_SCRIPT="/home/devops/RepoDevOps/packer-ansible/deployment.sh"

# Read the input from stdin
while read oldrev newrev refname
do
   #Check if the pushed branch is the main branch
   if [ "$refname" == "refs/heads/main" ]; then
        echo "Push to main branch detected. Executing remote script..."

        # Set the remote branch to main
        echo "$(ssh -p 2222 "$SSH_USER@$SSH_HOST" "git checkout main")"

        # Pull the latest changes from the remote branch
        echo "$(ssh -p 2222 "$SSH_USER@$SSH_HOST" "git pull")"

        # Execute the remote script
        SSH_OUTPUT=$(ssh -p 2222 "$SSH_USER@$SSH_HOST" "$REMOTE_SCRIPT")
        SSH_STATUS=$?

        #Check if the SSH command succeeded
        if [[ $SSH_STATUS -eq 0 ]]; then
            echo "##### Deployment script completed successfully on the production server. #####"
            echo "$SSH_OUTPUT"
        else
            echo "##### Deployment script failed on the production server.#####"
            echo "$SSH_OUTPUT"
            exit 1
        fi
   fi
done

