---
- name: Manage Docker containers
  hosts: localhost
  collections:
    - community.docker

  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create and start the my-scopus container
      docker_container:
        name: my-scopus-container
        image: vcampagnano/my-scopus-image
        pull: always
        state: started
        networks:
          - name: "devops-net"
            ipv4_address: 192.168.100.103
            aliases: "scopus-service"
        ports:
          - "8003:8003"

    - name: Create and start the my-scholar container
      docker_container:
        name: my-scholar-container
        image: vcampagnano/my-scholar-image
        pull: always
        state: started
        networks:
          - name: "devops-net"
            ipv4_address: 192.168.100.102
            aliases: "scholar-service"
        ports:
          - "8002:8002"
        
    - name: Create and start the my-cineca container
      docker_container:
        name: my-cineca-container
        image: vcampagnano/my-cineca-image
        pull: always
        state: started
        networks:
          - name: "devops-net"
            ipv4_address: 192.168.100.101
            aliases: "cineca-service"
        ports:
          - "8001:8001"
        
    - name: Create and start the my-search container
      docker_container:
        name: my-search-container
        image: vcampagnano/my-search-image
        pull: always
        state: started
        networks:
          - name: "devops-net"
            ipv4_address: 192.168.100.100
            aliases: "search-service"
        ports:
          - "8000:8000"