- hosts: localhost
  tasks:
    - name: Remove test containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - my-scopus-container-test
        - my-scholar-container-test
        - my-cineca-container-test
        - my-search-container-test