- hosts: localhost
  tasks:
    - name: Stop test containers 
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop:
        - my-scopus-container-test
        - my-scholar-container-test
        - my-cineca-container-test
        - my-search-container-test
